### ISSUE TITLE
封面图片会显示在文章里面

### ISSUE THREAD

**Issue by HAHAHUI** [XeonKHJ/InkingNewstand#25]

**Comment by XeonKHJ** [comment]
可以通过检测封面图片是否在文章里，有的话变不显示封面图片

**Comment by XeonKHJ** [comment]
已修正，发布在dev分支里。

**Comment by HAHAHUI** [comment]
页面不会显示相同的两张图片了，但是点开封面没有图片的新闻链接时会出现错误，直接跳到程序那报错。
            if(new Uri(News.CoverUrl) == new Uri(HtmlConverter.GetFirstImages(html)))//该行出错
            {
                headerImg.Visibility = Visibility.Collapsed;
            }
            else
            {
                headerImg.Visibility = Visibility.Visible;
            }
        }

**Comment by XeonKHJ** [comment]
> 页面不会显示相同的两张图片了，但是点开封面没有图片的新闻链接时会出现错误，直接跳到程序那报错。
> if(new Uri(News.CoverUrl) == new Uri(HtmlConverter.GetFirstImages(html)))//该行出错
> {
> headerImg.Visibility = Visibility.Collapsed;
> }
> else
> {
> headerImg.Visibility = Visibility.Visible;
> }
> }

没图片时用一个不合规范的字符串新建Uri实例会报错，已修复。

**Comment by HAHAHUI** [comment]
已测试，修复成功。
